### ISSUE TITLE
Advanced Tutorial Master Issue

### ISSUE THREAD

**Issue by Flashing-Blinkenlights** [avdstaaij/gdpc#1]
**Feature branch: `5.1`**

This issue attempts to outline and organise the goals for the GDPC 5.x advanced tutorial.

## Goals
1. The generator demonstrates all major and most minor features of GDPC (see **Features**)
2. The generator fulfils the minimum viable product requirements (see **MVP**)
3. The generator contains code and systems that may be easily modified for use in other projects
4. The generator is creative and unique and can provide inspiration for other participants
5. The generator fulfils the technical requirements for GDPC 2022 (see **Requirements**)
6. The generator is submitted to GDPC 2022 and achieves an above-average score

## Roadmap
See Projects -> Advanced Tutorial

## Requirements
- Runtime <= 10 minutes
- RAM usage <= 2GB 
- Can handle a build area of 1000x255x1000
- Player is positioned in the centre of the build area (and directed towards generated settlement)
- Can handle generated and player-made structures

## MVP
1.Fulfils competition requirements
2. Places settlement in sensible location
3. Uses template structures
4. Uniform paths connect structures to spawn point
5. Pre-existing structures are avoided and ignored

#### World analysis:
- [x] Global slices
- [x] Biomes
- [ ] Obtrusiveness and optimal direction
- [ ] Versions
- [x] Block categories
#### World manipulation:
- [ ] Interfaces
- [x] Running commands
- [ ] Manipulating build area
- [x] Placing blocks (advanced)
- [ ] Placing geometric shapes (advanced)
- [ ] Placing lecterns, signs, blocks with inventory
#### Utility:
- [x] 2D/3D loops
- [ ] Book writing
- [ ] Speeding up ticks for tree growth
#### Optimisation:
- [x] Keeping time
- [x] Caching
- [ ] Buffering
- [ ] Hint: LRU Cache

## Generator Architecture
4-phase process:
1. World analysis
2. Settlement setup/essentials/plot reservation
3. Settlement expansion and improvement (variable, finite length of time)
4. Settlement cleanup and beautification (remaining time)

**Comment by avdstaaij** [comment]
The advanced tutorial is no longer being worked on by its original developer @Flashing-Blinkenlights, and will likely become outdated soon. It is now considered to be out of scope of the library.
An advanced tutorial may return in the future, possibly in a different form.
